[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
goerli = '${GOERLI}'
mumbai = '${MUMBAI}'
arbitrum_goerli = '${ARBITRUM_GOERLI}'

[etherscan]
goerli = {key = '${ETHERSCAN}'}
mumbai = {key = '${POLYGONSCAN}'}
arbitrum_goerli = {key = '${ARBISCAN}'}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
